// Join Existing Fleet form — Sery Link v1 scaffold.
//
// Rendered on machine #2 after install (or from Settings) to redeem a
// pair code generated by machine #1. On success, the backend issues a
// 30-day agent token and the Rust side auto-saves it to the keyring —
// so the calling UI just needs to refresh its agent state after the
// onPaired callback fires.
//
// Deliberately lightweight:
//   * No QR scanner — users paste or type the code from the other machine.
//   * Hostname-based default display name (e.g. "MacBook Pro").
//   * Errors shown inline, no toast dependency.
//
// Paired backend: api/app/api/v1/agent_pairing.py pair-complete.

import { useState } from 'react';
import { invoke } from '@tauri-apps/api/core';

type PairCompleteResponse = {
  access_token: string;
  agent_id: string;
  workspace_id: string;
  expires_in?: number;
};

interface Props {
  onClose: () => void;
  onPaired?: (token: PairCompleteResponse) => void;
  // Optional suggestion (e.g. from hostname detection). Purely cosmetic.
  defaultDisplayName?: string;
}

export function JoinFleetForm({ onClose, onPaired, defaultDisplayName }: Props) {
  const [code, setCode] = useState('');
  const [displayName, setDisplayName] = useState(defaultDisplayName ?? '');
  const [submitting, setSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const canSubmit = normalizedCode(code).length === 12 && displayName.trim().length > 0 && !submitting;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;
    setSubmitting(true);
    setErrorMsg(null);
    try {
      const result = await invoke<PairCompleteResponse>('pair_complete', {
        pairCode: normalizedCode(code),
        displayName: displayName.trim(),
      });
      onPaired?.(result);
    } catch (err) {
      setErrorMsg(messageFromError(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-40 flex items-center justify-center bg-black/50"
      onClick={onClose}
      role="presentation"
    >
      <form
        onSubmit={handleSubmit}
        onClick={e => e.stopPropagation()}
        className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl dark:bg-slate-900"
        aria-labelledby="join-fleet-title"
      >
        <div className="mb-4 flex items-start justify-between">
          <h2 id="join-fleet-title" className="text-lg font-semibold text-slate-900 dark:text-slate-50">
            Join Existing Fleet
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <p className="mb-4 text-sm text-slate-600 dark:text-slate-400">
          On the machine already running Sery, open <strong>Add another machine</strong> and
          enter the code shown here.
        </p>

        <label className="block">
          <span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">
            Pair code
          </span>
          <input
            type="text"
            value={code}
            onChange={e => setCode(e.target.value.toUpperCase())}
            placeholder="XXX-XXX-XXX-XXX"
            autoFocus
            autoComplete="off"
            spellCheck={false}
            className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 font-mono text-lg tracking-wider text-slate-900 focus:border-purple-500 focus:outline-none focus:ring-1 focus:ring-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-50"
          />
          <span className="mt-1 block text-xs text-slate-500 dark:text-slate-400">
            12 characters, hyphens optional
          </span>
        </label>

        <label className="mt-4 block">
          <span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">
            Name this machine
          </span>
          <input
            type="text"
            value={displayName}
            onChange={e => setDisplayName(e.target.value)}
            placeholder="e.g. Home Desktop"
            maxLength={64}
            className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900 focus:border-purple-500 focus:outline-none focus:ring-1 focus:ring-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-50"
          />
        </label>

        {errorMsg && (
          <div className="mt-4 rounded-md border border-rose-300 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300">
            {errorMsg}
          </div>
        )}

        <div className="mt-6 flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg px-3 py-1.5 text-sm font-medium text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={!canSubmit}
            className="rounded-lg bg-purple-600 px-4 py-2 text-sm font-semibold text-white hover:bg-purple-700 disabled:cursor-not-allowed disabled:bg-slate-300 dark:disabled:bg-slate-700"
          >
            {submitting ? 'Connecting…' : 'Connect'}
          </button>
        </div>
      </form>
    </div>
  );
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function normalizedCode(raw: string): string {
  return raw.replace(/-/g, '').replace(/\s/g, '').toUpperCase();
}

function messageFromError(err: unknown): string {
  // Rust-side errors come back as strings via the invoke error path.
  const s = String(err);
  if (s.includes('410')) return 'This code expired or is no longer valid. Ask for a fresh code.';
  if (s.includes('409')) return 'This code has already been used. Ask for a fresh code.';
  if (s.includes('400')) return 'The code looks wrong. Double-check the characters.';
  if (s.includes('429')) return 'Too many attempts. Wait a minute and try again.';
  if (s.toLowerCase().includes('network') || s.toLowerCase().includes('connection')) {
    return "Can't reach Sery. Check your internet and retry.";
  }
  return s;
}
