//! F54 — Password storage for Agent-based JDBC database sources.
//!
//! The agent-driven DB sources (Oracle, DB2, SAP HANA, Teradata, etc.)
//! keep all connection metadata in `SourceKind::AgentDb` for display +
//! reuse, but the password belongs in the OS keychain so it's never
//! written to disk in cleartext.
//!
//! Service name: `"sery-agent-db"`. The account key is the source_id
//! (UUIDv4 generated by `add_agent_db_source`), giving us a stable
//! per-source slot in the keychain that lives and dies with the
//! `DataSource` entry in `config.json`.
//!
//! Goes through `crate::cred_store` (the encrypted-vault mirror of
//! `keyring::Entry`) so behaviour matches the rest of the credential
//! modules (gdrive_creds, webdav_creds, db_creds, etc.).

use crate::cred_store::{Entry, Error};

const SERVICE: &str = "sery-agent-db";

/// Persist `password` against `source_id` in the OS keychain.
///
/// Overwrites an existing entry if present — callers typically
/// delete-and-re-store rather than update in place, but `set_password`
/// is idempotent on every supported backend so this is safe to call
/// repeatedly.
pub fn store_password(source_id: &str, password: &str) -> Result<(), String> {
    let entry = Entry::new(SERVICE, source_id)
        .map_err(|e| format!("keyring open ({SERVICE}/{source_id}): {e}"))?;
    entry
        .set_password(password)
        .map_err(|e| format!("keyring set ({SERVICE}/{source_id}): {e}"))
}

/// Return the password stored for `source_id`, or an error if no
/// entry exists (i.e. the source was added but the keychain row was
/// later removed out-of-band).
pub fn load_password(source_id: &str) -> Result<String, String> {
    let entry = Entry::new(SERVICE, source_id)
        .map_err(|e| format!("keyring open ({SERVICE}/{source_id}): {e}"))?;
    entry
        .get_password()
        .map_err(|e| format!("keyring get ({SERVICE}/{source_id}): {e}"))
}

/// Best-effort delete. Returns Ok(()) if the entry was removed or if
/// it didn't exist; only opaque keychain errors propagate.
#[allow(dead_code)]
pub fn delete_password(source_id: &str) -> Result<(), String> {
    let entry = Entry::new(SERVICE, source_id)
        .map_err(|e| format!("keyring open ({SERVICE}/{source_id}): {e}"))?;
    match entry.delete_password() {
        Ok(()) => Ok(()),
        Err(Error::NoEntry) => Ok(()),
        Err(e) => Err(format!("keyring delete ({SERVICE}/{source_id}): {e}")),
    }
}
